(*
 * symbol_correspondence_map.ml
 *
 * Cross-Prover Symbol & Type Correspondence Map
 * Generated by XSLT Constraint Inversion Engine
 *
 * Purpose: Establish HOL ↔ Lean ↔ Agda bijections for all formal symbols,
 * enabling semantic verification across prover boundaries.
 *
 * Authority: GENERATED_UNVERIFIED
 * Status: Ready for HOL compilation and correspondence checking
 *)

(* ============================================================
   TYPE CORRESPONDENCE TABLE
   ============================================================ *)

(*
   HOL Type              Lean Type              Agda Type
   --------              ---------              ---------
   bool                  Bool                   Bool
   nat                   Nat                    ℕ
   int                   Int                    ℤ
   real                  ℝ                      ℝ
   'a list               List α                 List α
   'a * 'b               α × β                  α × β
   'a option             Option α               Maybe α
   graph                 Graph                  Graph
   system_state          SystemState            SystemState
   canonical_structure   CanonicalStructure     CanonicalStructure
   component             Component              Component

   Quantifiers:
   !x.P                  ∀ x, P x              ∀ x → P x
   ?x.P                  ∃ x, P x              ∃ x × P x

   Logical Operators:
   P ∧ Q                 P ∧ Q                 P ∧ Q
   P ∨ Q                 P ∨ Q                 P ∨ Q
   ~P                    ¬P                     ¬ P
   P ⟹ Q                 P → Q                 P → Q
   P ↔ Q                 P ↔ Q                 P ↔ Q
*)

(* ============================================================
   CONSTRAINT KIND MAPPING
   ============================================================ *)

type hol_constraint_kind =
  | Prohibition
  | Technology
  | BooleanAlgebra
  | RefinementType
  | GraphInvariant
  | OrderInvariant
  | EquivalenceClass
;;

let constraint_kind_to_lean : hol_constraint_kind -> string = function
  | Prohibition -> "ConstraintKind.Prohibition"
  | Technology -> "ConstraintKind.Technology"
  | BooleanAlgebra -> "ConstraintKind.BooleanAlgebra"
  | RefinementType -> "ConstraintKind.RefinementType"
  | GraphInvariant -> "ConstraintKind.GraphInvariant"
  | OrderInvariant -> "ConstraintKind.OrderInvariant"
  | EquivalenceClass -> "ConstraintKind.EquivalenceClass"
;;

let constraint_kind_to_agda : hol_constraint_kind -> string = function
  | Prohibition -> "ConstraintKind.prohibition"
  | Technology -> "ConstraintKind.technology"
  | BooleanAlgebra -> "ConstraintKind.boolean-algebra"
  | RefinementType -> "ConstraintKind.refinement-type"
  | GraphInvariant -> "ConstraintKind.graph-invariant"
  | OrderInvariant -> "ConstraintKind.order-invariant"
  | EquivalenceClass -> "ConstraintKind.equivalence-class"
;;

(* ============================================================
   POLARITY MAPPING
   ============================================================ *)

type hol_polarity =
  | Positive
  | Negative
  | Neutral
;;

let polarity_to_lean : hol_polarity -> string = function
  | Positive -> "Polarity.Positive"
  | Negative -> "Polarity.Negative"
  | Neutral -> "Polarity.Neutral"
;;

let polarity_to_agda : hol_polarity -> string = function
  | Positive -> "polarity-positive"
  | Negative -> "polarity-negative"
  | Neutral -> "polarity-neutral"
;;

(* ============================================================
   PREDICATE SYMBOL CORRESPONDENCE
   ============================================================ *)

type correspondence_record = {
  hol_symbol : string;
  hol_type : string;
  lean_symbol : string;
  lean_type : string;
  agda_symbol : string;
  agda_type : string;
  canonical_id : string;
  verification_status : string;
};;

let predicate_correspondence : correspondence_record list = [
  {
    hol_symbol = "system_valid";
    hol_type = "system_state -> bool";
    lean_symbol = "HyperKitty.SystemValid";
    lean_type = "SystemState → Prop";
    agda_symbol = "HyperKitty.system-valid";
    agda_type = "SystemState → Set";
    canonical_id = "CORR-PRED-001";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "is_forbidden_state";
    hol_type = "system_state -> bool";
    lean_symbol = "HyperKitty.isForbiddenState";
    lean_type = "SystemState → Prop";
    agda_symbol = "HyperKitty.is-forbidden-state";
    agda_type = "SystemState → Set";
    canonical_id = "CORR-PRED-002";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "has_cycle";
    hol_type = "graph -> bool";
    lean_symbol = "HyperKitty.hasCycle";
    lean_type = "Graph → Prop";
    agda_symbol = "HyperKitty.has-cycle";
    agda_type = "Graph → Set";
    canonical_id = "CORR-PRED-003";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "is_acyclic";
    hol_type = "graph -> bool";
    lean_symbol = "HyperKitty.isAcyclic";
    lean_type = "Graph → Prop";
    agda_symbol = "HyperKitty.is-acyclic";
    agda_type = "Graph → Set";
    canonical_id = "CORR-PRED-004";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "all_edges_valid";
    hol_type = "graph -> bool";
    lean_symbol = "HyperKitty.allEdgesValid";
    lean_type = "Graph → Prop";
    agda_symbol = "HyperKitty.all-edges-valid";
    agda_type = "Graph → Set";
    canonical_id = "CORR-PRED-005";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "valid_path";
    hol_type = "system_state -> system_state -> bool";
    lean_symbol = "HyperKitty.validPath";
    lean_type = "SystemState → SystemState → Prop";
    agda_symbol = "HyperKitty.valid-path";
    agda_type = "SystemState → SystemState → Set";
    canonical_id = "CORR-PRED-006";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "refines";
    hol_type = "('a -> bool) -> ('a -> bool) -> bool";
    lean_symbol = "HyperKitty.refines";
    lean_type = "(α → Prop) → (α → Prop) → Prop";
    agda_symbol = "HyperKitty.refines";
    agda_type = "(α → Set) → (α → Set) → Set";
    canonical_id = "CORR-PRED-007";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "pipeline_ordered";
    hol_type = "nat list -> bool";
    lean_symbol = "HyperKitty.pipelineOrdered";
    lean_type = "List Nat → Prop";
    agda_symbol = "HyperKitty.pipeline-ordered";
    agda_type = "List ℕ → Set";
    canonical_id = "CORR-PRED-008";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "accept";
    hol_type = "system_state -> bool";
    lean_symbol = "HyperKitty.accept";
    lean_type = "SystemState → Prop";
    agda_symbol = "HyperKitty.accept";
    agda_type = "SystemState → Set";
    canonical_id = "CORR-PRED-009";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "reject";
    hol_type = "system_state -> bool";
    lean_symbol = "HyperKitty.reject";
    lean_type = "SystemState → Prop";
    agda_symbol = "HyperKitty.reject";
    agda_type = "SystemState → Set";
    canonical_id = "CORR-PRED-010";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "is_fatal_violation";
    hol_type = "system_state -> bool";
    lean_symbol = "HyperKitty.isFatalViolation";
    lean_type = "SystemState → Prop";
    agda_symbol = "HyperKitty.is-fatal-violation";
    agda_type = "SystemState → Set";
    canonical_id = "CORR-PRED-011";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "satisfies_acceptance_criterion";
    hol_type = "system_state -> bool";
    lean_symbol = "HyperKitty.satisfiesAcceptanceCriterion";
    lean_type = "SystemState → Prop";
    agda_symbol = "HyperKitty.satisfies-acceptance-criterion";
    agda_type = "SystemState → Set";
    canonical_id = "CORR-PRED-012";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "extends";
    hol_type = "system_state -> system_state -> bool";
    lean_symbol = "HyperKitty.extends";
    lean_type = "SystemState → SystemState → Prop";
    agda_symbol = "HyperKitty.extends";
    agda_type = "SystemState → SystemState → Set";
    canonical_id = "CORR-PRED-013";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "is_canonical_structure";
    hol_type = "canonical_structure -> bool";
    lean_symbol = "HyperKitty.isCanonicalStructure";
    lean_type = "CanonicalStructure → Prop";
    agda_symbol = "HyperKitty.is-canonical-structure";
    agda_type = "CanonicalStructure → Set";
    canonical_id = "CORR-PRED-014";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "preserves_closure";
    hol_type = "canonical_structure -> bool";
    lean_symbol = "HyperKitty.preservesClosure";
    lean_type = "CanonicalStructure → Prop";
    agda_symbol = "HyperKitty.preserves-closure";
    agda_type = "CanonicalStructure → Set";
    canonical_id = "CORR-PRED-015";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "preserves_associativity";
    hol_type = "canonical_structure -> bool";
    lean_symbol = "HyperKitty.preservesAssociativity";
    lean_type = "CanonicalStructure → Prop";
    agda_symbol = "HyperKitty.preserves-associativity";
    agda_type = "CanonicalStructure → Set";
    canonical_id = "CORR-PRED-016";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "preserves_identity";
    hol_type = "canonical_structure -> bool";
    lean_symbol = "HyperKitty.preservesIdentity";
    lean_type = "CanonicalStructure → Prop";
    agda_symbol = "HyperKitty.preserves-identity";
    agda_type = "CanonicalStructure → Set";
    canonical_id = "CORR-PRED-017";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "isomorphic";
    hol_type = "canonical_structure -> canonical_structure -> bool";
    lean_symbol = "HyperKitty.isomorphic";
    lean_type = "CanonicalStructure → CanonicalStructure → Prop";
    agda_symbol = "HyperKitty.isomorphic";
    agda_type = "CanonicalStructure → CanonicalStructure → Set";
    canonical_id = "CORR-PRED-018";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "bijective";
    hol_type = "('a -> 'b) -> bool";
    lean_symbol = "HyperKitty.bijective";
    lean_type = "(α → β) → Prop";
    agda_symbol = "HyperKitty.bijective";
    agda_type = "(α → β) → Set";
    canonical_id = "CORR-PRED-019";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "preserves_ops";
    hol_type = "('a -> 'b) -> bool";
    lean_symbol = "HyperKitty.preservesOps";
    lean_type = "(α → β) → Prop";
    agda_symbol = "HyperKitty.preserves-ops";
    agda_type = "(α → β) → Set";
    canonical_id = "CORR-PRED-020";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "precondition";
    hol_type = "component -> 'a -> bool";
    lean_symbol = "HyperKitty.precondition";
    lean_type = "Component → α → Prop";
    agda_symbol = "HyperKitty.precondition";
    agda_type = "Component → α → Set";
    canonical_id = "CORR-PRED-021";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "postcondition";
    hol_type = "component -> 'a -> 'b -> bool";
    lean_symbol = "HyperKitty.postcondition";
    lean_type = "Component → α → β → Prop";
    agda_symbol = "HyperKitty.postcondition";
    agda_type = "Component → α → β → Set";
    canonical_id = "CORR-PRED-022";
    verification_status = "GENERATED_UNVERIFIED";
  };
  {
    hol_symbol = "execute";
    hol_type = "component -> 'a -> 'b";
    lean_symbol = "HyperKitty.execute";
    lean_type = "Component → α → β";
    agda_symbol = "HyperKitty.execute";
    agda_type = "Component → α → β";
    canonical_id = "CORR-PRED-023";
    verification_status = "GENERATED_UNVERIFIED";
  };
];;

(* ============================================================
   VERIFICATION AXIOMS FOR CORRESPONDENCE
   ============================================================ *)

(*
 * Correspondence Axioms: These assert that if HOL proves a theorem,
 * then its Lean and Agda counterparts share the same semantic meaning.
 *
 * These are NOT axioms in the mathematical sense (which would require
 * external justification). Rather, they are OBLIGATIONS: statements
 * that must be proven by explicit correspondence proofs in the
 * cross-prover verification phase.
 *)

let verification_axioms : string list = [
  (* Axiom 1: Type correspondence preserves semantics *)
  "AXIOM-CORR-001: If HOL proves P:bool, and Lean has P':Prop with same symbol origin,
   and Agda has P':Set with same symbol origin, then semantic equivalence holds:
   ⟦P⟧_HOL = ⟦P'⟧_Lean = ⟦P''⟧_Agda (requires external correspondence proof).";

  (* Axiom 2: Logical operator correspondence *)
  "AXIOM-CORR-002: Logical operators AND, OR, NOT, IMPLIES preserve meaning across
   HOL ∧, Lean ∧, Agda ∧ (requires proof that all three evaluate identically).";

  (* Axiom 3: Quantifier correspondence *)
  "AXIOM-CORR-003: Universal quantifier ∀ in HOL, Lean, Agda have equivalent scope
   and binding semantics (requires proof of quantifier substitution equivalence).";

  (* Axiom 4: Function application correspondence *)
  "AXIOM-CORR-004: Function application HOL f x, Lean f x, Agda f x evaluate to
   the same result (requires proof of applicative functor equivalence).";

  (* Axiom 5: Proof obligation correspondence *)
  "AXIOM-CORR-005: If HOL obligation O is proven in HOL, and Lean obligation O' is
   syntactically derived from O's symbol table, and Agda obligation O'' is derived
   from O', then all three discharges represent the same mathematical fact (requires
   external correspondence auditor to confirm).";
];;

(* ============================================================
   CORRESPONDENCE PROOF TEMPLATES
   ============================================================ *)

(*
 * Proof templates for cross-prover correspondence.
 * Each template shows the structure of a correspondence proof,
 * indicating what must be proven to establish semantic equivalence.
 *)

let correspondence_proof_templates : (string * string) list = [
  ("template-boolean-equivalence",
   {|Lean proof that HOL boolean obligation ⟺ Lean boolean obligation:

     theorem hol_lean_bool_equiv (p q : Prop) :
       (HOL.of_lean (p ∧ q)) = (HyperKitty.and p q) := by
         rfl  -- Assumes identity semantics
   |});

  ("template-graph-preservation",
   {|Lean proof that graph operations preserve structure:

     theorem hol_lean_graph_equiv (g : Graph) :
       (HOL.acyclic_of g) = (HyperKitty.isAcyclic g) := by
         cases g
         simp [HOL.acyclic_of, HyperKitty.isAcyclic]
   |});

  ("template-predicate-strengthening",
   {|Lean proof that refined predicates maintain refinement order:

     theorem hol_lean_refine_equiv (P Q : α → Prop) :
       (HOL.refines P Q) = (HyperKitty.refines P Q) := by
         unfold HOL.refines HyperKitty.refines
         simp [implies_iff_right]
   |});

  ("template-agda-verification",
   {|Agda proof that Lean correspondence corresponds to Agda:

     agda-correspondence : ∀ {p q : Set} →
       (Lean.of_agda (p ∧ q)) ≡ (HyperKitty.and p q)
     agda-correspondence = λ p q → refl
   |});
];;

(* ============================================================
   INVARIANT TO CORRESPONDENCE MAPPING
   ============================================================ *)

type invariant_correspondence = {
  invariant_id : string;
  invariant_kind : string;
  hol_obligation_ref : string;
  lean_theorem_ref : string;
  agda_proof_ref : string;
  correspondence_proof_required : bool;
  status : string;
};;

let invariant_correspondences : invariant_correspondence list = [
  {
    invariant_id = "INV-0001-PROHIBITION-FORBIDDEN-STATE";
    invariant_kind = "PROHIBITION";
    hol_obligation_ref = "invariant_0001_obligation";
    lean_theorem_ref = "HyperKitty.ConstraintInversionValidator.prohibition_sound";
    agda_proof_ref = "HyperKitty.ConstraintInversionValidator.prohibition-sound";
    correspondence_proof_required = true;
    status = "GENERATED_UNVERIFIED";
  };
  {
    invariant_id = "INV-0002-BOOLEAN-ALGEBRA-AND-PRESERVATION";
    invariant_kind = "BOOLEAN_ALGEBRA";
    hol_obligation_ref = "invariant_0002_obligation";
    lean_theorem_ref = "HyperKitty.Core.jordan_scalar_mul_commutative";
    agda_proof_ref = "HyperKitty.Core.jordan-scalar-mul-commutative";
    correspondence_proof_required = true;
    status = "GENERATED_UNVERIFIED";
  };
  {
    invariant_id = "INV-0003-BOOLEAN-ALGEBRA-DEMORGAN-AND";
    invariant_kind = "BOOLEAN_ALGEBRA";
    hol_obligation_ref = "invariant_0003_obligation";
    lean_theorem_ref = "HyperKitty.ConstraintInversionValidator.demorgan_and";
    agda_proof_ref = "HyperKitty.ConstraintInversionValidator.demorgan-and";
    correspondence_proof_required = true;
    status = "GENERATED_UNVERIFIED";
  };
  {
    invariant_id = "INV-0004-BOOLEAN-ALGEBRA-DEMORGAN-OR";
    invariant_kind = "BOOLEAN_ALGEBRA";
    hol_obligation_ref = "invariant_0004_obligation";
    lean_theorem_ref = "HyperKitty.ConstraintInversionValidator.demorgan_or";
    agda_proof_ref = "HyperKitty.ConstraintInversionValidator.demorgan-or";
    correspondence_proof_required = true;
    status = "GENERATED_UNVERIFIED";
  };
  {
    invariant_id = "INV-0005-GRAPH-INVARIANT-DAG-ACYCLIC";
    invariant_kind = "GRAPH_INVARIANT";
    hol_obligation_ref = "invariant_0005_obligation";
    lean_theorem_ref = "HyperKitty.NAND.dag_acyclic";
    agda_proof_ref = "HyperKitty.NAND.dag-acyclic";
    correspondence_proof_required = true;
    status = "GENERATED_UNVERIFIED";
  };
  {
    invariant_id = "INV-0006-GRAPH-INVARIANT-EDGE-CONSISTENCY";
    invariant_kind = "GRAPH_INVARIANT";
    hol_obligation_ref = "invariant_0006_obligation";
    lean_theorem_ref = "HyperKitty.NAND.edge_consistency";
    agda_proof_ref = "HyperKitty.NAND.edge-consistency";
    correspondence_proof_required = true;
    status = "GENERATED_UNVERIFIED";
  };
  {
    invariant_id = "INV-0013-ACCEPTANCE-CRITERION-SOUNDNESS";
    invariant_kind = "ACCEPTANCE";
    hol_obligation_ref = "invariant_0013_obligation";
    lean_theorem_ref = "HyperKitty.Witness.acceptance_sound";
    agda_proof_ref = "HyperKitty.Witness.acceptance-sound";
    correspondence_proof_required = true;
    status = "GENERATED_UNVERIFIED";
  };
];;

(* ============================================================
   AUTHORITY & VERIFICATION CHECKLIST
   ============================================================ *)

let verification_checklist : string list = [
  "[ ] HOL Light: Load constraint_obligations.ml and check type declarations";
  "[ ] HOL Light: All 18 proof obligations parse without syntax error";
  "[ ] HOL Light: All type signatures in invariant_NNNN_obligation are well-typed";
  "[ ] Lean 4: Parse all Lean theorem references from symbol table";
  "[ ] Lean 4: Type-check correspondence proofs (0 sorry terms)";
  "[ ] Agda 2: Type-check all 18 Agda proof references";
  "[ ] Agda 2: Generate 20 × 18 = 360 derivation obligations (distinct_derivation_obligations)";
  "[ ] Agda 2: Verify all 360 iterations type-check without postulates";
  "[ ] Cross-prover: Verify symbol_correspondence_map establishes HOL↔Lean bijection";
  "[ ] Cross-prover: Verify symbol_correspondence_map establishes Lean↔Agda bijection";
  "[ ] WORM Archive: Record this verification session with timestamp and authority chain";
];;

(* ============================================================
   EXECUTION COMMAND SEQUENCE
   ============================================================ *)

let execution_sequence : string list = [
  "Phase 5 (HOL Emit - THIS FILE):";
  "  $ ocaml constraint_obligations.ml";
  "  Output: 18 proof obligations emitted";
  "";
  "Phase 6 (HOL Verify):";
  "  $ hol";
  "  # use \"constraint_obligations.ml\";;";
  "  # type_of invariant_0001_obligation;;";
  "  # check symbol_table;;";
  "";
  "Phase 7 (Lean Emit):";
  "  Generate Lean declarations from HOL symbol_correspondence_map";
  "  References: ConstraintInversionValidator.lean";
  "";
  "Phase 8 (Lean Verify):";
  "  $ lean --check constraint_obligations_lean.lean";
  "  Output: All theorems compile, 0 sorry terms";
  "";
  "Phase 9 (Agda Emit):";
  "  Generate Agda declarations from Lean symbol_correspondence_map";
  "  References: ConstraintInversionValidator.agda (to be created)";
  "";
  "Phase 10 (Agda Verify):";
  "  $ agda constraint_obligations_agda.agda";
  "  Output: All proofs type-check";
  "";
  "Phase 11 (Agda 20x Iterations):";
  "  For each of 18 invariants, generate 20 indexed derivation proofs";
  "  Total: 360 distinct_derivation_obligations";
  "";
  "Phase 12 (Correspondence Check):";
  "  Verify HOL↔Lean↔Agda semantic equivalence";
  "  Authority: External correspondence auditor confirms or rejects";
];;

(* ============================================================
   END OF SYMBOL CORRESPONDENCE MAP
   ============================================================ *)
